include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "archive/**"  # 排除归档的旧代码
    - ".dart_tool/**"

  errors:
    # 将一些警告降级为info
    invalid_annotation_target: ignore
    todo: ignore

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # 启用推荐规则
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - unnecessary_brace_in_string_interps
    - unnecessary_to_list_in_spreads

    # 禁用一些过于严格的规则
    - use_build_context_synchronously: false
    - library_prefixes: false
